name: myworkflow
on:
  push: 
    branches: [main]

jobs:
  bulid:
    runs-on: unbuntu-lastest
    
    steps:
    - uses: actions/checkout@v2
    - name: Check for changes
      id: check_changes
      run: echo ::set-output name=commit_hash::$(git rev-parse HEAD)
    - name: my action
      if: ${{ github.event_name == 'push' && github.sha == steps.check_changes.outputs.commit_hash }}
      run: echo "byebye"
      
    
